name: rtx-java Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macOS-latest']
    env:
      TERM: dumb
    steps:
    - uses: actions/checkout@v3
    - uses: jdxcode/rtx-action@v1
      with:
        tool_versions: |
          jq 1.6
          shellcheck 0.9.0
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run ShellCheck
      run: |
        shellcheck -V
        shellcheck ./bin/functions
        shellcheck ./update_data.bash
    - name: Run tests
      run: |
        rtx plugins link .
        rtx i java@lts
        rtx x -- java -version
