name: Update Java release data
on:
  workflow_dispatch:
  schedule:
    - cron: '30 */8 * * *'
  push:
    branches:
      - update-data
jobs:
  update:
    if: github.repository == 'rtx-plugins/rtx-java'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - uses: jdxcode/rtx-action@v1
      with:
        tool_versions: |
          jq 1.6
    - name: Run update script
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export PATH=".:$PATH"
        ./update_data.bash
    - name: Commit files
      run: |
        git config --local user.email "123107610+rtx-vm@users.noreply.github.com"
        git config --local user.name "rtx"
        git add data/*.tsv
        git clean -f
        git commit -m "Update Java release data" || true
        git push
